### ISSUE TITLE
RAM Size boards.txt Entry Consistency

### ISSUE THREAD

**Issue by rei-vilo** [energia/msp432-core#3]
Updated `boards.txt` for **MSP432** and **MSP430** uses `maximum_data_size`

> MSP-EXP432P401R.upload.maximum_data_size=65536
> MSP-EXP430F5529LP.upload.maximum_data_size=8192

when **Tiva C** and **CC3200** use `maximum_ram_size`

> EK-LM4F120XL.upload.maximum_ram_size=32768
> # CC3200-LAUNCHXL.upload.maximum_ram_size=32768

**Comment by robertinant** [comment]
For TivaC this was fixed with commit https://github.com/energia/tivac-core/commit/c4446f677baa96373af15cc4294be6e9eaed02da
CC3200 ram_size / data_size does not apply since it is all RAM and I am using upload.maximum_size for that. I just committed a patch that removes the redundant upload.maximum_ram_size for CC3200: 90ef3bcdcd5cb626c9491976d17d3b30d265f050
